stages:
  - test

.test:
  stage: test
  cache:
    paths:
      - .mygo/pkg/mod
  script:
    - GOPATH=$(pwd)/.mygo go install github.com/jstemmer/go-junit-report
    - GOPATH=$(pwd)/.mygo go test -v -coverprofile .testCoverage.txt ./... 2>&1 | $(pwd)/.mygo/bin/go-junit-report -set-exit-code > test.xml
    - GOPATH=$(pwd)/.mygo go tool cover -func=.testCoverage.txt
  after_script:
    # GOPROXY packages are not deletable by default
    - chmod -R u+w .mygo/pkg/mod
  artifacts:
    reports:
      junit: test.xml

test-podman:
  extends: .test
  before_script:
    - podman pull docker.io/hello-world
  tags:
    - podman

test-docker:
  extends: .test
  before_script:
    - docker pull docker.io/hello-world
  tags:
    - docker
